env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
globals:
  process: true
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - "prettier"
rules:
  {
    quotes: [error, single],
    object-curly-spacing: [error, always],
    "prettier/prettier": "error"
  }
